name: Publish NuGet Package

on:
  push:
    tags:
      - "v*.*.*"  # Runs only when you push a version tag like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Authenticate with GitHub Packages
        run: |
          dotnet nuget add source --username NytraOG \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-cleartext \
            --name github "https://nuget.pkg.github.com/NytraOG/index.json"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build --output nupkgs

      - name: Publish NuGet Package to GitHub Packages
        run: dotnet nuget push nupkgs/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
